BluCorpWeb/Controllers/EmpresaController.cs
using BluDataList.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BluDataList.Controllers
{
    public class EmpresaController : Controller
    {
        DAO dao = new DAO();
        // GET: Empresa
        public ActionResult Index()
        {
            var lista = dao.MostrarEmpresas();
            return View(lista);
        }
        public ActionResult Fornecedores(int id, string uf)
        {
            var lista = dao.MostrarFornecedor(id);
            ViewBag.Idempresa = id;
            ViewBag.Estado = uf;
            return View(lista);
        }
        public ActionResult CriaEmpresa()
        {
            return View();
        }
        public ActionResult CriarFornecedor(int idEmpresa, string estado)
        {
            ViewBag.Idempresa = idEmpresa;
            ViewBag.Estado = estado;
            return View();
        }
        public ActionResult SalvaEmpresa(string nome, string cnpj, string UF)
        {
            dao.InserirEmpresa(nome, cnpj, UF);
            return RedirectToAction("Index");
        }
        public ActionResult SalvaFornecedor(string nome, string cnpj, string telefone,string rg, string nascimento, string estado, string id)
        {
            var dados = DateTime.Parse(DateTime.Now.ToString("dd/MM/yyyy"));
            DateTime data = DateTime.Parse(nascimento);
            var contaNumeros = cnpj.Replace(".","").Replace("/","").Replace("-","");
            if (estado == "PR" && contaNumeros.Length == 11)
            {
                var novaData = data.AddYears(+18);
                if (novaData > dados)
                {
                    return View();
                }
            }
            data.ToString("dd/MM/yyyy");
            dao.InserirFornecedor(nome,cnpj,telefone,rg,data.ToString(),estado,id);
            return RedirectToAction("Index");
        }
        public ActionResult DeleEmpresa(int id)
        {
            dao.DeletaEmpresa(id);
            return RedirectToAction("Index");
        } public ActionResult DeleFornecedor(int id)
        {
            dao.DeletaFornecedor(id);
            return RedirectToAction("Index");
        }
    }
}

BluCorpWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:red">
        <div class="container">
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BluWebCorp", "Index", "Empresa", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BluWebCorp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>